<a href="https://colab.research.google.com/github/Joaogalescky/Ciencia-de-Dados---2024/blob/main/Jo%C3%A3o_Vitor_Camp%C3%B5e_Galescky_Trabalho_1%C2%BA_Bimestre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trabalho 1º Bimestre

## 1- Base Datatran






**Dicas**
- Assim como nos DataFrames, nas Series também é possível utilizar a função `.head()`.
- A função `.value_counts()` retorna os valores ordenados por quantidade, em ordem decrescente.

In [4]:
import pandas as pd
import numpy as np

In [5]:
########################
#Leitura da base no diretório local (Jupyter)
########################
# df = pd.read_csv('./bases/datatran2018.csv', sep=';', encoding='latin-1') # Carrega a base

########################
#Leitura da base no Google Drive (Colaboratory)
########################
from google.colab import drive
drive.mount('/drive') #monta a base no google drive
database_path = '/drive/Shareddrives/BasesPublicas/Bases/PRF/datatran2018.csv' #caminho da base de dados
df = pd.read_csv(database_path, sep=';', encoding='latin-1') #Carrega a base

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).


In [ ]:
df.shape #Mostra o número de linhas e colunas na base

(69295, 30)

In [ ]:
df.info() #Mostra informações sobre a base

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69295 entries, 0 to 69294
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   id                      69295 non-null  float64
 1   data_inversa            69295 non-null  object 
 2   dia_semana              69295 non-null  object 
 3   horario                 69295 non-null  object 
 4   uf                      69295 non-null  object 
 5   br                      69181 non-null  float64
 6   km                      69181 non-null  object 
 7   municipio               69295 non-null  object 
 8   causa_acidente          69295 non-null  object 
 9   tipo_acidente           69295 non-null  object 
 10  classificacao_acidente  69295 non-null  object 
 11  fase_dia                69295 non-null  object 
 12  sentido_via             69295 non-null  object 
 13  condicao_metereologica  69295 non-null  object 
 14  tipo_pista              69295 non-null

In [ ]:
df.head(5) #Observa as primeiras linhas da base

id data_inversa     dia_semana   horario  uf     br     km  \
0  99973.0   2018-01-01  segunda-feira  00:20:00  RJ  116.0  303,5   
1  99976.0   2018-01-01  segunda-feira  00:40:00  SC  282.0    0,4   
2  99977.0   2018-01-01  segunda-feira  00:30:00  RJ  493.0      1   
3  99981.0   2018-01-01  segunda-feira  01:15:00  RS  386.0    134   
4  99982.0   2018-01-01  segunda-feira  00:20:00  RS  293.0  151,7   

       municipio                      causa_acidente  \
0        RESENDE                   Condutor Dormindo   
1  FLORIANOPOLIS  Não guardar distância de segurança   
2       ITABORAI              Ultrapassagem Indevida   
3        SARANDI                  Ingestão de Álcool   
4       CANDIOTA         Falta de Atenção à Condução   

               tipo_acidente  ... feridos_graves ilesos ignorados feridos  \
0  Saída de leito carroçável  ...              4      1         0       4   
1           Colisão traseira  ...              2      1         0       2   
2            Colisão frontal  ...              0      3         1       1   
3        Colisão transversal  ...              0      2         0       0   
4  Saída de leito carroçável  ...              1      0         0       1   

  veiculos      latitude     longitude  regional  delegacia       uop  
0        1     -22,46937     -44,44705     SR-RJ     DEL5/7  UOP03/RJ  
1        2  -27,59971687  -48,57565694     SR-SC     DEL8/1  UOP01/SC  
2        3    -22,763901    -42,927532     SR-RJ     DEL5/4  UOP02/RJ  
3        2    -27,953636    -52,916374     SR-RS    DEL9/14  UOP01/RS  
4        1    -31,395214  -53,78391174     SR-RS    DEL9/11  UOP03/RS  

[5 rows x 30 columns]

In [ ]:
df.tail(5) #Observa as ultimas linhas da base

id data_inversa     dia_semana   horario  uf     br     km  \
69290  252256.0   2018-12-24  segunda-feira  09:15:00  PI  343.0  263,1   
69291  252652.0   2018-12-12   quarta-feira  07:00:00  BA  101.0    321   
69292  252801.0   2018-11-15   quinta-feira  10:48:00  SP  116.0    529   
69293  253040.0   2018-11-23    sexta-feira  19:30:00  RS  472.0  573,5   
69294  253078.0   2018-10-01  segunda-feira  04:31:00  GO   40.0      9   

                       municipio  \
69290                CAMPO MAIOR   
69291  PRESIDENTE TANCREDO NEVES   
69292             BARRA DO TURVO   
69293                 URUGUAIANA   
69294                   LUZIANIA   

                                          causa_acidente  \
69290                                   Agressão Externa   
69291                        Falta de Atenção à Condução   
69292                        Falta de Atenção à Condução   
69293  Desobediência às normas de trânsito pelo condutor   
69294                 Não guardar distância de segurança   

                      tipo_acidente  ... feridos_graves ilesos ignorados  \
69290   Colisão com objeto estático  ...              0      1         0   
69291     Saída de leito carroçável  ...              0      0         0   
69292              Colisão traseira  ...              0      0         1   
69293  Queda de ocupante de veículo  ...              1      1         0   
69294     Saída de leito carroçável  ...              0      0         0   

      feridos veiculos      latitude     longitude  regional  delegacia  \
69290       0        1     -4,819326    -42,158821     SR-PI    DEL17/1   
69291       1        1  -13,44768518  -39,42066193     SR-BA    DEL10/5   
69292       1        2    -24,939211    -48,301248     SR-SP     DEL6/5   
69293       1        2  -29,76355779  -57,05200195     SR-RS    DEL9/13   
69294       1        1    -16,131158    -47,957739     SR-DF   UOP01/DF   

            uop  
69290  UOP03/PI  
69291  UOP03/BA  
69292  UOP03/SP  
69293  UOP01/RS  
69294       NaN  

[5 rows x 30 columns]

In [ ]:
df.columns #mostra as colunas presentes na base

Index(['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km',
       'municipio', 'causa_acidente', 'tipo_acidente',
       'classificacao_acidente', 'fase_dia', 'sentido_via',
       'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo',
       'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos',
       'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional',
       'delegacia', 'uop'],
      dtype='object')

**Item 01**  
- Qual é o estado que teve o maior número de acidentes?

In [ ]:
estado_acidentes = df['uf'].value_counts()
estado_acidentes.head(1)

uf
MG    9066
Name: count, dtype: int64

**Item 02**  
- Apresente a quantidade de acidentes por dia da semana.

In [ ]:
dia_semana_acidentes = df['dia_semana'].value_counts()
dia_semana_acidentes

dia_semana
domingo          11283
sábado           11239
sexta-feira      10632
segunda-feira     9422
quinta-feira      9230
quarta-feira      8824
terça-feira       8665
Name: count, dtype: int64

**Item 03**  
- Apresente a quantidade de acidentes por estado.

In [ ]:
dia_estado_acidentes = df['uf'].value_counts()
dia_estado_acidentes

uf
MG    9066
SC    8497
PR    7952
RJ    4575
SP    4516
RS    4445
BA    3555
GO    3464
PE    2715
ES    2642
MT    2631
CE    1697
RO    1629
PB    1588
MS    1530
RN    1416
PI    1371
MA    1272
PA    1260
DF     867
AL     691
TO     589
SE     559
RR     236
AC     235
AP     173
AM     124
Name: count, dtype: int64

**Item 04**  
- De acordo com a quantidade de acidentes, quais são as 5 rodovias mais perigosas?

In [ ]:
rodovia_acidentes = df['br'].value_counts()
rodovia_acidentes.head(5)

br
101.0    11212
116.0     9972
381.0     3550
40.0      3220
153.0     2834
Name: count, dtype: int64

**Item 05**  
- Considerando apenas acidentes com vítimas fatais, qual rodovia é a mais perigosa?

In [ ]:
rodovia_fatais = df.groupby('br')['mortos'].sum()  # Somar o número total de mortos por rodovia
rodovia_mais_fatais = rodovia_fatais.idxmax()  # Encontrar o índice da rodovia com o maior número de mortos
total_mortos_rodovia_fatal = rodovia_fatais.max()

print("Nome da rodovia (BR) mais fatal:", rodovia_mais_fatais)
print("Total de mortos na rodovia mais fatal:", total_mortos_rodovia_fatal)

Índice da rodovia (BR) mais fatal: 116.0
Total de mortos na rodovia mais fatal: 649


**Item 06**  
- No Paraná, quais são as 10 cidades do interior que possuiram o maior número de acidentes?

In [ ]:
# Filtrar dados para o Paraná e suas cidades
df_pr_interior = df[(df['uf'] == 'PR') & (df['municipio'])]

cidades_parana_m_acidentes = df_pr_interior['municipio'].value_counts()

cidades_parana_m_acidentes.head(10)

municipio
CURITIBA                 1019
SAO JOSE DOS PINHAIS      448
MARINGA                   443
CASCAVEL                  338
FOZ DO IGUACU             299
CAMPINA GRANDE DO SUL     285
PONTA GROSSA              268
PARANAGUA                 178
APUCARANA                 156
CAMPO LARGO               153
Name: count, dtype: int64

**Item 07**  
- Os acidentes com vítimas fatais ocorrem em sua maioria em trechos de curvas ou de reta?

In [ ]:
trechos_mortes = df.groupby('tracado_via')['mortos'].sum()
trechos_m_mortes = trechos_mortes.idxmax()

print("Os acidentes com maiores vítimas fatais ocorre com trechos do tipo:", trechos_m_mortes)

Os acidentes com maiores vítimas fatais ocorre com trechos do tipo: Reta


**Item 08**  
- Quais são as 10 maiores causas de acidentes?

In [ ]:
maiores_acidentes = df['causa_acidente'].value_counts()
maiores_acidentes.head(10)

causa_acidente
Falta de Atenção à Condução                          25830
Desobediência às normas de trânsito pelo condutor     7189
Velocidade Incompatível                               6849
Ingestão de Álcool                                    5201
Não guardar distância de segurança                    4262
Defeito Mecânico no Veículo                           3716
Condutor Dormindo                                     2633
Pista Escorregadia                                    2549
Falta de Atenção do Pedestre                          2073
Animais na Pista                                      1614
Name: count, dtype: int64

**Item 09**  
- Em que estado ocorre o maior número de acidentes em que a causa foi animais na pista?

In [ ]:
m_estado_por_animais = df[(df['causa_acidente'] == 'Animais na Pista') & (df['uf'])]

m_estado_maior_acidentes_animais = m_estado_por_animais['uf'].value_counts()

m_estado_maior_acidentes_animais.head(1)

uf
MG    198
Name: count, dtype: int64

**Item 10**  
- Em Cascavel, no Paraná, qual são as rodovias que existem na base de dados?

In [ ]:
cascavel_rodovias = df[(df['municipio'] == 'CASCAVEL') & (df['uf'] == 'PR')]
cascavel_rodovias_existem = cascavel_rodovias['br'].unique()
print(cascavel_rodovias_existem)

[277. 467. 369.  nan 163.]


**Item 11**  
- Em Cascavel, no Paraná, qual é a rodovia que mais possui acidentes?

In [ ]:
cascavel_rodovias = df[(df['municipio'] == 'CASCAVEL') & (df['uf'] == 'PR')]
cascavel_rodovias_acidentes = cascavel_rodovias['br'].value_counts()
cascavel_rodovias_acidentes.head(1)

br
277.0    242
Name: count, dtype: int64

**Item 12**  
- Em Cascavel, no Paraná, em qual kilômetro da rodovia BR 277 ocorreram o maior número de acidentes com vítimas fatais? Obs: por padrão a coluna `br` está com valores do tipo `float`. (`277.0`).

In [ ]:
cascavel_rodovias_277 = cascavel_rodovias
cascavel_rodovias_277 = df[df['br'] == 277]
cascavel_rodovias_277['km'].value_counts()

km
729      24
584      17
724      15
723      14
660      14
         ..
598,1     1
605       1
133,1     1
349,3     1
74,7      1
Name: count, Length: 1151, dtype: int64

**Item 13**  
- Realize uma outra análise utilizando algum critério elaborado por você, e explique o resultado obtido.

In [ ]:
cascavel_rodovias = df[(df['municipio'] == 'CASCAVEL') & (df['uf'] == 'PR')]
cascavel_maiores_tipos_acidente = cascavel_rodovias
cascavel_maiores_tipos_acidente = df['causa_acidente'].value_counts()
print("As 10 maiores causas de acidentes nas rodovias relacionadas a Cascavel/PR: ")
print(cascavel_maiores_tipos_acidente.head(10))
print("--------------------------------------------------------------------------")
print("As 10 menores causas de acidentes nas rodovias relacionadas a Cascavel/PR: ")
print(cascavel_maiores_tipos_acidente.tail(10))

# A intenção do resultado obtido é analisar quais os 10 tipos de acidentes que mais e menos ocorrem nas rodovias relacionadas ao munícipio de Cascavel/PR.

As 10 maiores causas de acidentes nas rodovias relacionadas a Cascavel/PR: 
causa_acidente
Falta de Atenção à Condução                          25830
Desobediência às normas de trânsito pelo condutor     7189
Velocidade Incompatível                               6849
Ingestão de Álcool                                    5201
Não guardar distância de segurança                    4262
Defeito Mecânico no Veículo                           3716
Condutor Dormindo                                     2633
Pista Escorregadia                                    2549
Falta de Atenção do Pedestre                          2073
Animais na Pista                                      1614
Name: count, dtype: int64
--------------------------------------------------------------------------
As 10 menores causas de acidentes nas rodovias relacionadas a Cascavel/PR: 
causa_acidente
Restrição de Visibilidade                                                         539
Objeto estático sobre o leito carroçável 

## 2 - Base Transparencia PR

Acesse o [Portal da Transparência do Governo do Estado do Paraná](http://www.transparencia.pr.gov.br). Faça o download da base de servidores do estado, clicando em **Pessoal -> Remuneração -> Download do Banco de Dados -> Download** (deixar marcado Informações Funcionais - Arquivo único).

Em seguida, carregue a base.

Sobre a base responda:
- Quais são as variáveis presentes na base?
- A que corresponde cada registro na base?

Com a base carregada, faça:

1. Filtre a base, mantendo apenas servidores ativos

Em seguida, responda às seguintes perguntas:

1. Nos registros, há quantos servidores nos regimes de trabalho CLT, CRES, estatutário, temporário e outros?

1. Quais são as instituições de ensino superior estaduais do Paraná (IEES)?

1. No quadro funcional de IEES, há servidores de quais cidades?

1. No quadro funcional de IEES, há quantos tipos de cargo?

1. Há quantos professores em Cascavel?

1. Há quantos professores de ensino superior em Cascavel (cargo "PROFESSOR")?

1. Qual é a quantidade de homens e mulheres que trabalham em Cascavel?

1. Qual é a quantidade de homens e mulheres que trabalham em Cascavel, em termos percentuais?

1. Qual é remuneracao média dos homens que trabalham em Londrina?

1. Qual é remuneracao média das mulheres que trabalham em Londrina?

1. Quais são os 10 nomes que mais se repetem na base de dados?

1. Pode-se afirmar que o nome "MARIA APARECIDA DA SILVA", que aparece 24 vezes corresponde a 24 pessoas distintas?




In [6]:
from google.colab import drive
drive.mount('/drive') #monta a base no google drive
database_path = '/drive/MyDrive/REMUNERACAO_RH/TB_RH.csv' #caminho da base de dados
df_RH = pd.read_csv(database_path, sep=';') #Carrega a base

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).


1. Filtre a base, mantendo apenas servidores ativos

In [7]:
dfAtivos = df_RH[df_RH['situacao'] == 'ATIVO']
dfAtivos

cod_vinculo                          nome     sigla  \
26           500612  RODRIGO MARCO LOPES DE SEHLI    PRPREV   
30           401166                 ROSELIA COSTA      SEED   
32            36630                SERGIO BOTELHO      SEED   
37           291237              SILVANA DE SOUZA      SEED   
38           294651              SIRLENE GARBOSSA      SEED   
...             ...                           ...       ...   
814310       486063     FABIANE CARVALHO TEIXEIRA    PRPREV   
814320       132644           GILDA SANTOS BORGES      SEED   
814345       501707              JANAINA DE ASSIS    PRPREV   
814411       504454        MIRIAM RENATA SILVEIRA    PRPREV   
814414       489300     PATRICIA BROCHADO BARRETO  PRCIDADE   

                   instituicao                      lotacao municipio  \
26           PARANAPREVIDÊNCIA                           DJ  CURITIBA   
30      SECRETARIA DA EDUCAÇÃO                     PALMEIRA  PALMEIRA   
32      SECRETARIA DA EDUCAÇÃO                       XAMBRE    XAMBRE   
37      SECRETARIA DA EDUCAÇÃO                      PINHAIS   PINHAIS   
38      SECRETARIA DA EDUCAÇÃO                         VERE      VERE   
...                        ...                          ...       ...   
814310       PARANAPREVIDÊNCIA                           DJ  CURITIBA   
814320  SECRETARIA DA EDUCAÇÃO         COL EST PEDRO MACEDO  CURITIBA   
814345       PARANAPREVIDÊNCIA                         PRES  CURITIBA   
814411       PARANAPREVIDÊNCIA                           DJ  CURITIBA   
814414           PARANÁ CIDADE  PROCURADORIA JURIDICA - PJU  CURITIBA   

                        cargo   dt_inicio dt_fim       regime  \
26                ADVOGADO SR  2001-05-02    NaN          CLT   
30                  PROFESSOR  2005-12-20    NaN  ESTATUTÁRIO   
32                  PROFESSOR  2006-04-17    NaN  ESTATUTÁRIO   
37                  PROFESSOR  2012-04-02    NaN  ESTATUTÁRIO   
38                  PROFESSOR  2005-12-20    NaN  ESTATUTÁRIO   
...                       ...         ...    ...          ...   
814310               ADVOGADO  2013-11-04    NaN          CLT   
814320              PROFESSOR  2009-02-03    NaN  ESTATUTÁRIO   
814345  ANALISTA DE PROCESSOS  2013-07-01    NaN          CLT   
814411               ADVOGADO  2008-05-05    NaN          CLT   
814414               ADVOGADO  1997-02-03    NaN          CLT   

       quadro_funcional quadro_funcional_desc tipo_cargo situacao  \
26        ADM. INDIRETA         ADM. INDIRETA       ****    ATIVO   
30                  QPM            MAGISTÉRIO    EFETIVO    ATIVO   
32                  QPM            MAGISTÉRIO    EFETIVO    ATIVO   
37                  QPM            MAGISTÉRIO    EFETIVO    ATIVO   
38                  QPM            MAGISTÉRIO    EFETIVO    ATIVO   
...                 ...                   ...        ...      ...   
814310    ADM. INDIRETA         ADM. INDIRETA       ****    ATIVO   
814320              QPM            MAGISTÉRIO    EFETIVO    ATIVO   
814345    ADM. INDIRETA         ADM. INDIRETA       ****    ATIVO   
814411    ADM. INDIRETA         ADM. INDIRETA       ****    ATIVO   
814414    ADM. INDIRETA         ADM. INDIRETA       ****    ATIVO   

        ult_remu_bruta genero  ano_nasc  atualizado  
26            19276.82      M    1974.0  2024-04-11  
30             4813.15      F    1973.0  2024-04-01  
32             4813.15      M    1971.0  2024-04-01  
37             4024.50      F    1970.0  2024-04-01  
38             8517.34      F    1980.0  2024-04-01  
...                ...    ...       ...         ...  
814310        12824.58      F    1980.0  2024-04-11  
814320         6177.59      F    1966.0  2024-04-01  
814345         9660.41      F    1980.0  2024-04-11  
814411        14152.48      F    1973.0  2024-04-11  
814414        23770.00      F    1968.0  2024-04-01  

[161480 rows x 18 columns]

Em seguida, responda às seguintes perguntas:
1. Nos registros, há quantos servidores nos regimes de trabalho CLT, CRES, estatutário, temporário e outros?

In [ ]:
dfAtivos['regime'].value_counts()

regime
ESTATUTÁRIO    121538
TEMPORÁRIO      32942
CLT              4095
CRES             2696
OUTROS            209
Name: count, dtype: int64

2. Quais são as instituições de ensino superior estaduais do Paraná (IEES)?

In [ ]:
dfSuperior = dfAtivos[dfAtivos['quadro_funcional'] == 'IEES']
print(dfSuperior['instituicao'].unique())

['UNESPAR - CAMPUS DE CAMPO MOURÃO' 'UNESPAR - CAMPUS DE  PARANAGUA'
 'UNESPAR - CAMPUS DE CURITIBA I' 'UNESPAR - CAMPUS DE UNIAO DA VITORIA'
 'UNESPAR - CAMPUS DE CURITIBA II' 'UNESPAR - CAMPUS DE APUCARANA'
 'UNESPAR - CAMPUS DE PARANAVAI' 'UNIVERSIDADE ESTADUAL DE PONTA GROSSA'
 'UNIVERSIDADE ESTADUAL DE LONDRINA' 'UNIVERSIDADE ESTADUAL DE MARINGA'
 'UNIVERSIDADE ESTADUAL DO OESTE DO PARANA'
 'UNIVERSIDADE ESTADUAL DO CENTRO-OESTE' 'FACULDADE DE ARTES DO PARANÁ'
 'UNIVERSIDADE ESTADUAL DO NORTE DO PARANA'
 'UNIVERSIDADE ESTADUAL DO PARANÁ'
 'ESCOLA DE MÚSICAS BELAS ARTES DO PARANÁ'
 'FAC. EST. FIL. C. LET. UNIÃO DA VITÓRIA'
 'FAC. EST. CIÊNCIAS LET. CAMPO MOURÃO'
 'FAC. EST. FIL. C. LET. CORNÉLIO PROCÓPIO'
 'FAC. EST. FIL. CIÊNCIAS LET. PARANAGUA'
 'FAC. EST. CIÊNCIAS ECON. DE APUCARANA']


3. No quadro funcional de IEES, há servidores de quais cidades?

In [ ]:
dfSuperior = dfAtivos[dfAtivos['quadro_funcional'] == 'IEES']
print(dfSuperior['municipio'].unique())

['CAMPO MOURAO' 'PARANAGUA' 'CURITIBA' 'UNIAO DA VITORIA' 'APUCARANA'
 'PARANAVAI' 'PONTA GROSSA' 'LONDRINA' 'MARINGA' 'CASCAVEL' 'GUARAPUAVA'
 'JACAREZINHO' 'UMUARAMA' 'IRATI' 'BANDEIRANTES' 'FRANCISCO BELTRAO'
 'TOLEDO' 'MARECHAL CANDIDO RONDON' 'FOZ DO IGUACU' 'CIDADE GAUCHA'
 'GOIOERE' 'CIANORTE' 'DIAMANTE DO NORTE' 'IVAIPORA' 'CORNELIO PROCOPIO']


4. No quadro funcional de IEES, há quantos tipos de cargo?

In [ ]:
dfSuperior = dfAtivos[dfAtivos['quadro_funcional'] == 'IEES']
print(dfSuperior['cargo'].unique())

['PROFESSOR ENSINO SUPERIOR' 'AGENTE UNIVERSITÁRIO DE EXECUÇÃO'
 'AGENTE UNIVERSITÁRIO PROFISSIONAL' 'AGENTE UNIVERSITÁRIO DE APOIO'
 'PROFESSOR DE ENSINO SUPERIOR' 'AGENTE UNIV  EXECUCAO'
 'AG. UNIVERSITARIO OPERACIONAL' 'AGENTE UNIVERSITARIO'
 'AGENTE UNIV  PROFISSIONAL' 'AGENTE UNIV  APOIO'
 'AG. UNIVERSITARIO DE NIVEL MEDIO' 'CARGO EM COMISSÃO - DA-4'
 'CARGO EM COMISSÃO - FA-2' 'AG. UNIVERSITARIO NIVEL SUPERIOR'
 'CARGO EM COMISSAO SEM VINCULO' 'CARGO EM COMISSÃO - DA-3'
 'ASSESSOR TECNICO' 'CARGO EM COMISSÃO' 'CARGO EM COMISSÃO - DA-5'
 'CARGO COMISSAO 01' 'CARGO EM COMISSÃO - FA-1' 'CARGO EM COMISSÃO - FA-3'
 'AGENTE UNIVERSITÁRIO' 'ASSESSOR ESPECIAL' 'AGENTE UNIV  NIVEL SUPERIOR'
 'AGENTE UNIVERSITÁRIO DE NÍVEL SUPERIOR' 'CARGO EM COMISSÃO - DA-2'
 'AGENTE U. DE NÍVEL SUPERIOR' 'CARGO EM COMISSÃO - FA2'
 'APRENDIZ - ASSISTENTE ADMINIST' 'AGENTE U. DE NÍVEL MÉDIO'
 'ASSESSOR DE DIRETORIA' 'TECNICO DE LABORATORIO'
 'CARGO EM COMISSÃO - DA-1' 'AGENTE UNIVERSITÁRIO OPERACIONAL'
 'A

5. Há quantos professores em Cascavel?

In [10]:
dfCascavel = dfAtivos[dfAtivos['municipio'] == 'CASCAVEL']
dfProfessorCascavel = dfCascavel[dfCascavel['cargo'] == 'PROFESSOR']
print(dfProfessorCascavel.shape[0])

1333


6. Há quantos professores de ensino superior em Cascavel (cargo "PROFESSOR")?

In [13]:
# dfProfessorEnsinoSuperiorCascavel = dfAtivos[(dfAtivos['municipio'] == 'CASCAVEL') & (dfAtivos['quadro_funcional'] == 'IEES') & (dfAtivos['cargo'] == 'PROFESSOR')]
# ou
dfProfessorEnsinoSuperiorCascavel = dfProfessorCascavel[dfProfessorCascavel['quadro_funcional'] == 'IEES']
print(dfProfessorEnsinoSuperiorCascavel.shape[0])

0


7. Qual é a quantidade de homens e mulheres que trabalham em Cascavel?

In [36]:
dfCascavelGenero = dfCascavel['genero'].value_counts()
print(dfCascavelGenero)

genero
F    3802
M    1960
Name: count, dtype: int64


8. Qual é a quantidade de homens e mulheres que trabalham em Cascavel, em termos percentuais?

In [50]:
dfCascavelGeneroTotal = dfCascavelGenero.sum() #Calculo para descobrir o total de homens e mulheres em Cascavel/PR
print("Total de homens e mulheres que trabalham em Cascavel/PR: ", dfCascavelGeneroTotal)
print("--------------------------------------------------------------------------------")
dfCascavelGeneroPerc = (dfCascavelGenero / dfCascavelGeneroTotal) * 100
print("Percentual de homens e mulheres que trabalham em Cascavel/PR: ")
print(dfCascavelGeneroPerc)

Total de homens e mulheres que trabalham em Cascavel/PR:  5762
--------------------------------------------------------------------------------
Percentual de homens e mulheres que trabalham em Cascavel/PR: 
genero
F    65.984033
M    34.015967
Name: count, dtype: float64


9. Qual é remuneracao média dos homens que trabalham em Londrina?

In [80]:
dfLondrina = dfAtivos[dfAtivos['municipio'] == 'LONDRINA']
dfLondrinaHomens = dfLondrina[dfLondrina['genero'] == 'M']
dfLondrinaH_RemuneracaoTotal = dfLondrinaHomens['ult_remu_bruta'].sum()

nHomens = len(dfLondrinaHomens)
dfLondrinaHomens_Media_Remuneracao = dfLondrinaH_RemuneracaoTotal / nHomens
print("A remuneração média dos homens que trabalham em Londrina é R$ ", round(dfLondrinaHomens_Media_Remuneracao, 2))

A remuneração média dos homens que trabalham em Londrina é R$  11722.53


10. Qual é remuneracao média das mulheres que trabalham em Londrina?

In [81]:
dfLondrinaMulheres = dfLondrina[dfLondrina['genero'] == 'F']
dfLondrinaM_RemuneracaoTotal = dfLondrinaMulheres['ult_remu_bruta'].sum()

nMulheres = len(dfLondrinaMulheres)
dfLondrinaMulheres_Media_Remuneracao = dfLondrinaM_RemuneracaoTotal / nMulheres
print("A remuneração média das mulheres que trabalham em Londrina é R$ ", round(dfLondrinaMulheres_Media_Remuneracao, 2))

A remuneração média das mulheres que trabalham em Londrina é R$  10380.21


11. Quais são os 10 nomes que mais se repetem na base de dados?

In [85]:
df_RH_Nomes = df_RH['nome'].value_counts()
df_RH_Nomes.head(10)

nome
MARIA APARECIDA DA SILVA       182
MARIA APARECIDA DOS SANTOS     121
ANA PAULA DA SILVA              67
JOSE CARLOS DA SILVA            67
MARIA APARECIDA DE OLIVEIRA     59
ANTONIO CARLOS DA SILVA         56
JOSE CARLOS DOS SANTOS          55
VERA LUCIA DA SILVA             55
ANA PAULA DE OLIVEIRA           51
MARIA DE FATIMA DOS SANTOS      51
Name: count, dtype: int64

12. Pode-se afirmar que o nome "MARIA APARECIDA DA SILVA", que aparece 24 vezes corresponde a 24 pessoas distintas?

In [111]:
# Não, não pode-se afirmar que há 24 pessoas distintas somente pela repetição do campo nome,
# sendo necessárioa examinar outros dados de caráter único/pessoal para verificar se há pessoas distintas, como data de nascimento, CPF, número de celular etc.

# Entretanto, referente ao arquivo "REMUNERACAO_RH/TB_RH.csv", pode-se verificar pela operação a baixo a existencia de 182 pessoas distintas do mesmo nome,
# "MARIA APARECIDA DA SILVA", sendo justificado por representar unicamente o registro de remuneracao de cada agente e por conter seu codigo de vinculo.

dfNome = df_RH['nome'] == 'MARIA APARECIDA DA SILVA'
dfMaria = df_RH[dfNome]


valores_cod_vinculo = dfMaria['cod_vinculo'].unique()
print(valores_cod_vinculo)
print("----------------------------------------------------------------------")
num_valores_unicos_cod_vinculo = dfMaria['cod_vinculo'].nunique()
print("Número de valores únicos de cod_vinculo:", num_valores_unicos_cod_vinculo)

[412717 517555 125986 793439 714623 725816 722322 651906  32884  72624
  27168 532167 336931 832004 847177 462494 571531 674711 835039 292908
 277113 787803 409987 274523  65427  13502 299029 723512 135036  94379
 224572 177468 457627 369758 367529 560448 618312 632043 361314 379453
 381421  45570 434000 389155 313309 568511 612411 281783 426490 172787
 171079 101969 559074 599506 739273 277223 588844 180506 317336  31320
 568561 634568 307586 454084 370516 515049 204985  15004 171181 103859
 583761 431520 515219 294018  44632 165075  93822 654883 681052 264252
 450756 208179 504613  74848 295451 265966 350490 421011 365006 139310
  18698  10864 284486 524118 576194 172350 303955  60049  52681 464009
 600741 773199 826197 213947 240999 414004 300760 510718  51216  93829
 302543 395512 188869  10865 526644 577401 675989  21795 210887   2446
 203700 566383 613591 318388 401452 463540 612119  71510 409312  21273
 190903 347611 319411 299784  24884 209651 325294  89495  58110  53232
 52357